version: "3.8"

services:
  redis:
    image: redis:6.2.0
    env_file:
      - ./env/.redis.env
  registry:
    image: registry:2.7.1
    restart: unless-stopped
    volumes:
      - ./registry_data:/var/lib/registry
    env_file:
      - ./env/.registry.env
    depends_on:
      - redis
